name: deploy1.yml
on:
  pull_request:
    branches:
      - prod
    types:
      - closed
#  push:
#    branches:
#      - main
jobs:
  build-deploy:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install JAVA
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: SetUP Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.8.2'
      - name: Determinar o TIpo de Version pela Label
        id: version-type
        run: |
          echo "Verificando labels do PR..."
          LABELS=$(gh pr view ${{ github.event.pull_request.number }} --json labels -q ".labels[].name")
          VERSION_TYPE="patch"
          if echo "$LABELS" | grep -q 'version:major'; then VERSION_TYPE="major"; fi
          if echo "$LABELS" | grep -q 'version:minor'; then VERSION_TYPE="minor"; fi
           echo "version_type=$VERSION_TYPE" >> $GITHUB_OUTPUT
          echo "$VERSION_TYPE"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Bump Major Version
        id: bump
        run: |
          set -e 
          TYPE=${{ steps.version-type.outputs.version_type }}
          
          case "$TYPE" in
            major)   mvn -B -q build-helper:parse-version versions:set \
                       -DnewVersion=\${parsedVersion.nextMajorVersion}.0.0 \
                       -DprocessAllModules -DgenerateBackupPoms=false ;;
            minor)  mvn -B -q build-helper:parse-version versions:set \
                       -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}.0 \
                       -DprocessAllModules -DgenerateBackupPoms=false ;;
            patch) mvn -B -q build-helper:parse-version versions:set \
                       -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} \
                       -DprocessAllModules -DgenerateBackupPoms=false ;;
          esac
          NEW_VER="$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)"
          
            echo "Nova VersÃ£o: $NEW_VER"
            echo "version=$NEW_VER" >> "$GITHUB_OUTPUT"
      - name: Build Project
        run: mvn -B -DskipTests package

      - name: Commit POM.xml
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "githubbot ci: bump para a versao ${{steps.bump.outputs.version}}"
          file_pattern: 'pom.xml'
